import { test, expect } from "bun:test";
import { donationPair } from "./donationScoring";
import { noteStatus, noteTallyVisible, TALLY_REVEAL_AFTER_DAYS } from "./noteScore";
import { noteTally, probabilityHelpful, probabilityHelpfulAfter } from "./noteBelief";
import { regularizedIncompleteBeta } from "./incompleteBeta";
import type { NoteRow } from "./types";
import { VOTE_VALUES } from "../../../dashboard-shared/Ratings";
import type { Vote } from "./votes";

/** Covers the p-model cluster that donations rest on — `noteBelief` (the
 *  latent-quality estimate), `noteScore` (the rating rule built on it) and
 *  `donationScoring` (the pricing) — in one file, because the fixtures below
 *  assert the probability and the resulting donation together.
 *
 *  Fixtures generated by the model this port is derived from:
 *    uv run --with scipy src/scripts_jim/2026_07_21_donation_decay/decay.py
 *  Their job is to catch the TS and the Python silently drifting apart — the
 *  failure mode that let a double-rounding bug survive in the previous scheme.
 */
const CASES: { tally: [number, number, number]; vote: Vote; p: number; ifHelpful: number; ifNotHelpful: number }[] = [
  { tally: [0, 0, 0], vote: 1, p: 0.35, ifHelpful: 3.08, ifNotHelpful: 0.25 },
  { tally: [0, 0, 0], vote: 0, p: 0.35, ifHelpful: 2.44, ifNotHelpful: 0.95 },
  { tally: [0, 0, 0], vote: -1, p: 0.35, ifHelpful: 0.55, ifNotHelpful: 1.98 },
  { tally: [1, 0, 0], vote: 1, p: 0.576683, ifHelpful: 2.36, ifNotHelpful: 0.25 },
  { tally: [1, 0, 0], vote: 0, p: 0.576683, ifHelpful: 2.08, ifNotHelpful: 0.93 },
  { tally: [1, 0, 0], vote: -1, p: 0.576683, ifHelpful: 0.81, ifNotHelpful: 2.52 },
  { tally: [2, 0, 0], vote: 1, p: 0.745807, ifHelpful: 1.63, ifNotHelpful: 0.25 },
  { tally: [2, 0, 0], vote: 0, p: 0.745807, ifHelpful: 1.53, ifNotHelpful: 0.75 },
  { tally: [2, 0, 0], vote: -1, p: 0.745807, ifHelpful: 0.87, ifNotHelpful: 2.4 },
  { tally: [5, 0, 0], vote: 1, p: 0.959212, ifHelpful: 0.5, ifNotHelpful: 0.25 },
  { tally: [5, 0, 0], vote: 0, p: 0.959212, ifHelpful: 0.5, ifNotHelpful: 0.35 },
  { tally: [5, 0, 0], vote: -1, p: 0.959212, ifHelpful: 0.46, ifNotHelpful: 0.97 },
  { tally: [3, 0, 2], vote: 1, p: 0.659683, ifHelpful: 1.74, ifNotHelpful: 0.25 },
  { tally: [3, 0, 2], vote: 0, p: 0.659683, ifHelpful: 1.57, ifNotHelpful: 0.77 },
  { tally: [3, 0, 2], vote: -1, p: 0.659683, ifHelpful: 0.81, ifNotHelpful: 2.12 },
  { tally: [0, 0, 3], vote: 1, p: 0.101549, ifHelpful: 2.06, ifNotHelpful: 0.38 },
  { tally: [0, 0, 3], vote: 0, p: 0.101549, ifHelpful: 1.33, ifNotHelpful: 0.56 },
  { tally: [0, 0, 3], vote: -1, p: 0.101549, ifHelpful: 0.25, ifNotHelpful: 0.7 },
  { tally: [0, 4, 0], vote: 1, p: 0.745807, ifHelpful: 1.63, ifNotHelpful: 0.25 },
  { tally: [0, 4, 0], vote: 0, p: 0.745807, ifHelpful: 1.53, ifNotHelpful: 0.75 },
  { tally: [0, 4, 0], vote: -1, p: 0.745807, ifHelpful: 0.87, ifNotHelpful: 2.4 },
  { tally: [2, 1, 1], vote: 1, p: 0.699147, ifHelpful: 1.71, ifNotHelpful: 0.25 },
  { tally: [2, 1, 1], vote: 0, p: 0.699147, ifHelpful: 1.57, ifNotHelpful: 0.77 },
  { tally: [2, 1, 1], vote: -1, p: 0.699147, ifHelpful: 0.85, ifNotHelpful: 2.26 },
  { tally: [12, 0, 1], vote: 1, p: 0.999191, ifHelpful: 0.26, ifNotHelpful: 0.25 },
  { tally: [12, 0, 1], vote: 0, p: 0.999191, ifHelpful: 0.26, ifNotHelpful: 0.25 },
  { tally: [12, 0, 1], vote: -1, p: 0.999191, ifHelpful: 0.26, ifNotHelpful: 0.27 },
];

const note = (counts: Partial<NoteRow>): NoteRow =>
  ({ helpful_count: 0, somewhat_helpful_count: 0, not_helpful_count: 0, author_id: null, ...counts }) as NoteRow;

const asTally = ([helpful, somewhatHelpful, notHelpful]: [number, number, number]) => ({
  helpful,
  somewhatHelpful,
  notHelpful,
});

test("matches the Python model's probabilities", () => {
  for (const c of CASES) {
    expect(probabilityHelpful(asTally(c.tally))).toBeCloseTo(c.p, 5);
  }
});

test("matches the Python model's donation pairs to the cent", () => {
  for (const c of CASES) {
    expect(donationPair(asTally(c.tally), c.vote)).toEqual({
      ifHelpful: c.ifHelpful,
      ifNotHelpful: c.ifNotHelpful,
    });
  }
});

test("no displayed amount ever falls below the participation tip", () => {
  for (let helpful = 0; helpful <= 15; helpful++) {
    for (let notHelpful = 0; notHelpful <= 15; notHelpful++) {
      for (const vote of VOTE_VALUES) {
        const pair = donationPair({ helpful, somewhatHelpful: 0, notHelpful }, vote);
        expect(pair.ifHelpful).toBeGreaterThanOrEqual(0.25);
        expect(pair.ifNotHelpful).toBeGreaterThanOrEqual(0.25);
      }
    }
  }
});

test("donations decay as unanimous votes pile up", () => {
  const amounts = Array.from({ length: 8 }, (_, helpful) =>
    donationPair({ helpful, somewhatHelpful: 0, notHelpful: 0 }, 1).ifHelpful,
  );
  amounts.reduce((previous, amount) => {
    expect(amount).toBeLessThanOrEqual(previous);
    return amount;
  });
  expect(amounts[0]).toBeGreaterThan(2.5); // an early vote is worth real money
  expect(amounts[5]).toBeLessThan(0.6); // the sixth is not ($0.50)
});

test("the rating thresholds bracket the tallies Jim specified", () => {
  // Helpful: 2 Helpful alone is not enough; 2 Helpful + 1 Somewhat is.
  expect(noteStatus(note({ helpful_count: 2 }))).toBe("needs_ratings"); // p = 0.746
  expect(noteStatus(note({ helpful_count: 2, somewhat_helpful_count: 1 }))).toBe("helpful"); // p = 0.808
  // Unhelpful: 1 Not-helpful is not enough; 2 are.
  expect(noteStatus(note({ not_helpful_count: 1 }))).toBe("needs_ratings"); // p = 0.235
  expect(noteStatus(note({ not_helpful_count: 2 }))).toBe("not_helpful"); // p = 0.156
});

test("no single vote can rate a note, so no explicit quorum is needed", () => {
  expect(noteStatus(note({ helpful_count: 1 }))).toBe("needs_ratings"); // p = 0.577
  expect(noteStatus(note({ somewhat_helpful_count: 1 }))).toBe("needs_ratings"); // p = 0.469
  expect(noteStatus(note({ not_helpful_count: 1 }))).toBe("needs_ratings"); // p = 0.235
});

test("Somewhat votes only ever help, and enough of them rate a note helpful", () => {
  // Never evidence against: adding one to any tally cannot lower p.
  const base = { helpful: 2, somewhatHelpful: 0, notHelpful: 1 };
  expect(probabilityHelpful({ ...base, somewhatHelpful: 1 })).toBeGreaterThan(
    probabilityHelpful(base),
  );
  // ...but worth half a Helpful vote, not a whole one.
  expect(probabilityHelpful({ helpful: 2, somewhatHelpful: 1, notHelpful: 0 })).toBeLessThan(
    probabilityHelpful({ helpful: 3, somewhatHelpful: 0, notHelpful: 0 }),
  );
  // Accepted consequence (Jim): Somewhat votes alone eventually rate it helpful.
  expect(noteStatus(note({ somewhat_helpful_count: 4 }))).toBe("needs_ratings");
  expect(noteStatus(note({ somewhat_helpful_count: 5 }))).toBe("helpful");
});

test("probabilityHelpfulAfter previews the estimate one vote ahead (feed ranking)", () => {
  const twoHelpful = note({ helpful_count: 2 });
  const now = probabilityHelpful(noteTally(twoHelpful));
  expect(probabilityHelpfulAfter(twoHelpful, 1)).toBeGreaterThan(now);
  expect(probabilityHelpfulAfter(twoHelpful, -1)).toBeLessThan(now);
  // Equivalent to having actually received that vote.
  expect(probabilityHelpfulAfter(twoHelpful, 1)).toBeCloseTo(
    probabilityHelpful({ helpful: 3, somewhatHelpful: 0, notHelpful: 0 }),
    10,
  );
  // Ranking consequence: a note nearer the bar leads one further away.
  expect(probabilityHelpfulAfter(note({ helpful_count: 2 }), 1)).toBeGreaterThan(
    probabilityHelpfulAfter(note({ helpful_count: 1, not_helpful_count: 1 }), 1),
  );
});

test("the author's own self-vote is excluded from the tally", () => {
  expect(noteTally(note({ helpful_count: 3, author_id: "someone" })).helpful).toBe(2);
  expect(noteTally(note({ helpful_count: 3, author_id: null })).helpful).toBe(3);
});

test("regularized incomplete beta agrees with known closed forms", () => {
  expect(regularizedIncompleteBeta(1, 1, 0.42)).toBeCloseTo(0.42, 10); // uniform
  expect(regularizedIncompleteBeta(2, 1, 0.5)).toBeCloseTo(0.25, 10); // x^2
  expect(regularizedIncompleteBeta(3, 3, 0.5)).toBeCloseTo(0.5, 10); // symmetric
  expect(regularizedIncompleteBeta(5, 2, 0)).toBe(0);
  expect(regularizedIncompleteBeta(5, 2, 1)).toBe(1);
});

test("a rated note shows its tally to everyone; an unrated one only after you vote", () => {
  const fresh = new Date().toISOString();
  // Rated either way → counts are the result, nothing left to anchor on.
  expect(noteTallyVisible("helpful", undefined, fresh)).toBe(true);
  expect(noteTallyVisible("not_helpful", undefined, fresh)).toBe(true);
  // Still open → hidden until you've voted, or until it's old enough.
  expect(noteTallyVisible("needs_ratings", undefined, fresh)).toBe(false);
  expect(noteTallyVisible("needs_ratings", 1, fresh)).toBe(true);
  const old = new Date(Date.now() - (TALLY_REVEAL_AFTER_DAYS + 1) * 86_400_000).toISOString();
  expect(noteTallyVisible("needs_ratings", undefined, old)).toBe(true);
});
