/** Draws every logo file from the one glyph path in src/everything-ui/icons.tsx:
 *  the website's logo SVG, its favicons, the extension's icons, and the icons
 *  the browser stores ask for.
 *  The logo comes in two forms. In light mode it is the plain blue notes. In
 *  dark mode, wherever the icon sits on the browser's own grey, it is the blue
 *  notes on a black tile. Plain blue notes vanish on a mid grey: on the grey
 *  Chrome's dark toolbar puts behind a hovered button they measured 1.0 to 1,
 *  the same brightness. Blue on black is 4.1 to 1.
 *  It renders through Chrome with Playwright, because Playwright is already a
 *  dependency of this repo. macOS has no reliable command line SVG rasterizer.
 *  sips mangles SVGs, and rsvg-convert is not installed.
 *  The files are checked in, so run this again only when the glyph changes:
 *
 *    bun run scripts/generate-logo-assets.ts
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { chromium } from "playwright";
import { NOTE_STACK_GLYPH_PATH } from "../src/everything-ui/icons";

const ROOT = path.resolve(import.meta.dir, "..");
const LOGO_PATH = path.join(ROOT, "src/everything-ui/assets/logo.svg");
const EXTENSION_ICONS = path.join(ROOT, "src/everything-extension/public/icon");
const STORE_ASSETS = path.join(ROOT, "src/everything-extension/store-assets");
const WEBSITE_ASSETS = path.join(ROOT, "src/everything-web/src/assets");
const FAVICON_PATH = path.join(WEBSITE_ASSETS, "icon.svg");

// The brand blue, the primary colour in src/everything-ui/tokens.css.
const LOGO_COLOR = "#2563eb";
// Jim picked black for the dark mode tile in the logo explorer.
const DARK_TILE_COLOR = "#000000";
const GENERATED_NOTE = "<!-- Generated by scripts/generate-logo-assets.ts from NOTE_STACK_GLYPH_PATH in src/everything-ui/icons.tsx. -->";

// The glyph spans 18 of its 24 units, from 3 to 21. Alone, it is scaled up to
// fill the whole square. On the tile it takes 80 of 128 units, as the logo
// explorer's "Fit to canvas" leaves it on a backdrop. The tile's corners are
// rounded by 22% of its width. The explorer's tile presets use the same
// proportions.
const GLYPH_SPAN = 18;
const FILL_SCALE = 24 / GLYPH_SPAN;
const TILE_SCALE = ((80 / 128) * 24) / GLYPH_SPAN;
const TILE_CORNER_SHARE = 0.22;

const svg = (body: string) =>
  `<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 24 24">\n  ${GENERATED_NOTE}\n${body}</svg>\n`;
const scaledAroundCentre = (scale: number) => `translate(12 12) scale(${scale.toFixed(4)}) translate(-12 -12)`;
const notes = (scale: number) =>
  `  <path class="notes" fill="${LOGO_COLOR}" fill-rule="evenodd" transform="${scaledAroundCentre(scale)}" d="${NOTE_STACK_GLYPH_PATH}"/>\n`;
/** `cornerShare` 0 gives a square, for iOS, which rounds the corners itself. */
const tile = (cornerShare: number) => `  <rect class="tile" width="24" height="24" rx="${cornerShare * 24}" fill="${DARK_TILE_COLOR}"/>\n`;

const LOGO_SVG = svg(notes(FILL_SCALE));
const DARK_ICON_SVG = svg(tile(TILE_CORNER_SHARE) + notes(TILE_SCALE));
// The favicon switches with the reader's colour scheme by itself.
const FAVICON_SVG = svg(
  `  <style>.tile{display:none}@media (prefers-color-scheme: dark){.tile{display:inline}.notes{transform:translate(12px,12px) scale(${TILE_SCALE.toFixed(4)}) translate(-12px,-12px)}}</style>\n` +
    tile(TILE_CORNER_SHARE) +
    notes(FILL_SCALE),
);

interface Raster {
  file: string;
  svg: string;
  size: number;
  /** How wide the SVG is drawn inside the square. The rest stays transparent. */
  artwork: number;
}

// The Chrome Web Store asks for the 128 pixel icon to carry its artwork at 96
// by 96 inside a transparent margin. The manifest's 128 pixel icon is the same
// file. The smaller sizes fill their whole square. The dark mode icons are
// only needed at the toolbar's sizes.
const CHROME_128 = { svg: LOGO_SVG, size: 128, artwork: 96 };
const RASTERS: Raster[] = [
  { file: path.join(EXTENSION_ICONS, "16.png"), svg: LOGO_SVG, size: 16, artwork: 16 },
  { file: path.join(EXTENSION_ICONS, "32.png"), svg: LOGO_SVG, size: 32, artwork: 32 },
  { file: path.join(EXTENSION_ICONS, "48.png"), svg: LOGO_SVG, size: 48, artwork: 48 },
  { file: path.join(EXTENSION_ICONS, "128.png"), ...CHROME_128 },
  { file: path.join(EXTENSION_ICONS, "tile-16.png"), svg: DARK_ICON_SVG, size: 16, artwork: 16 },
  { file: path.join(EXTENSION_ICONS, "tile-32.png"), svg: DARK_ICON_SVG, size: 32, artwork: 32 },
  { file: path.join(STORE_ASSETS, "chrome-web-store-128.png"), ...CHROME_128 },
  // Mozilla's add-on listing wants a 128 pixel icon that fills its square.
  { file: path.join(STORE_ASSETS, "firefox-add-ons-128.png"), svg: LOGO_SVG, size: 128, artwork: 128 },
  // Browsers without SVG favicons take a PNG, one per colour scheme.
  { file: path.join(WEBSITE_ASSETS, "favicon-32.png"), svg: LOGO_SVG, size: 32, artwork: 32 },
  { file: path.join(WEBSITE_ASSETS, "favicon-dark-32.png"), svg: DARK_ICON_SVG, size: 32, artwork: 32 },
  // iOS puts anything transparent on black, so the home screen icon is the
  // dark form, as a full square.
  { file: path.join(WEBSITE_ASSETS, "apple-touch-icon.png"), svg: svg(tile(0) + notes(TILE_SCALE)), size: 180, artwork: 180 },
];

writeFileSync(LOGO_PATH, LOGO_SVG);
writeFileSync(FAVICON_PATH, FAVICON_SVG);
console.log(`wrote ${LOGO_PATH} and ${FAVICON_PATH}`);

// Chrome itself on a Mac, Playwright's own Chromium elsewhere.
const browser = await chromium.launch(process.platform === "darwin" ? { channel: "chrome" } : {});
const page = await browser.newPage();

for (const { file, svg: image, size, artwork } of RASTERS) {
  const inset = (size - artwork) / 2;
  await page.setViewportSize({ width: size, height: size });
  await page.setContent(
    `<style>html,body{margin:0;background:transparent}svg{display:block;width:${artwork}px;height:${artwork}px;margin:${inset}px}</style>${image}`,
  );
  await page.screenshot({ path: file, omitBackground: true });
  console.log(`wrote ${file}`);
}
await browser.close();
