/** Draws every logo file from the one glyph path in src/everything-ui/icons.tsx:
 *  the website's logo SVG, its favicons, the extension's icons, and the icons
 *  the browser stores ask for.
 *  It renders through Chrome with Playwright, because Playwright is already a
 *  dependency of this repo. macOS has no reliable command line SVG rasterizer.
 *  sips mangles SVGs, and rsvg-convert is not installed.
 *  The files are checked in, so run this again only when the glyph changes:
 *
 *    bun run scripts/generate-logo-assets.ts
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { chromium } from "playwright";
import { NOTE_STACK_GLYPH_PATH } from "../src/everything-ui/icons";

const ROOT = path.resolve(import.meta.dir, "..");
const LOGO_PATH = path.join(ROOT, "src/everything-ui/assets/logo.svg");
const EXTENSION_ICONS = path.join(ROOT, "src/everything-extension/public/icon");
const STORE_ASSETS = path.join(ROOT, "src/everything-extension/store-assets");
const WEBSITE_ASSETS = path.join(ROOT, "src/everything-web/src/assets");

// The brand blue, the primary colour in src/everything-ui/tokens.css.
const LOGO_COLOR = "#2563eb";
// The glyph spans 18 of its 24 units, from 3 to 21. Cropping the view to that
// square makes the mark fill the whole image.
const LOGO_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="3 3 18 18">
  <!-- Generated by scripts/generate-logo-assets.ts from NOTE_STACK_GLYPH_PATH in src/everything-ui/icons.tsx. -->
  <path fill="${LOGO_COLOR}" fill-rule="evenodd" d="${NOTE_STACK_GLYPH_PATH}"/>
</svg>
`;

interface Raster {
  file: string;
  size: number;
  /** How wide the mark is drawn inside the square. The rest is margin. */
  artwork: number;
  /** A fill behind the mark. Without one the margin stays transparent. */
  background?: string;
}

// The Chrome Web Store asks for the 128 pixel icon to carry its artwork at 96
// by 96 inside a transparent margin. The manifest's 128 pixel icon is the same
// file. The smaller toolbar sizes fill their whole square.
const CHROME_128 = { size: 128, artwork: 96 };
const RASTERS: Raster[] = [
  { file: path.join(EXTENSION_ICONS, "16.png"), size: 16, artwork: 16 },
  { file: path.join(EXTENSION_ICONS, "32.png"), size: 32, artwork: 32 },
  { file: path.join(EXTENSION_ICONS, "48.png"), size: 48, artwork: 48 },
  { file: path.join(EXTENSION_ICONS, "128.png"), ...CHROME_128 },
  { file: path.join(STORE_ASSETS, "chrome-web-store-128.png"), ...CHROME_128 },
  // Mozilla's add-on listing wants a 128 pixel icon that fills its square.
  { file: path.join(STORE_ASSETS, "firefox-add-ons-128.png"), size: 128, artwork: 128 },
  // Browsers without SVG favicons take the PNG.
  { file: path.join(WEBSITE_ASSETS, "favicon-32.png"), size: 32, artwork: 32 },
  // iOS puts a transparent home screen icon on black and rounds its corners
  // itself, so this one gets a white square and a margin.
  { file: path.join(WEBSITE_ASSETS, "apple-touch-icon.png"), size: 180, artwork: 128, background: "#ffffff" },
];

writeFileSync(LOGO_PATH, LOGO_SVG);
console.log(`wrote ${LOGO_PATH}`);

// Chrome itself on a Mac, Playwright's own Chromium elsewhere.
const browser = await chromium.launch(process.platform === "darwin" ? { channel: "chrome" } : {});
const page = await browser.newPage();

for (const { file, size, artwork, background = "transparent" } of RASTERS) {
  const inset = (size - artwork) / 2;
  await page.setViewportSize({ width: size, height: size });
  await page.setContent(
    `<style>html,body{margin:0;background:${background}}svg{display:block;width:${artwork}px;height:${artwork}px;margin:${inset}px}</style>${LOGO_SVG}`,
  );
  await page.screenshot({ path: file, omitBackground: background === "transparent" });
  console.log(`wrote ${file}`);
}
await browser.close();
