/**
 * The fixed Community Note we submit when Pangram flags a post as AI-generated.
 * The Pangram report URL doubles as the note's (required) source link.
 */
import { countSubmittedNoteLength } from "../utils/noteLength";

const NOTE_BODY =
  "The text of this post was very likely generated by AI, according to Pangram, a leading AI-text detection tool. Full analysis:";

// X caps notes at 280 chars; URLs count as 1. A constant body + one link is well
// under, but guard so a future wording change can't silently ship an over-limit note.
const MAX_NOTE_LENGTH = 280;

export type PangramNote = { noteText: string; sourceUrl: string };

/** Returns the submitted note (body + report link) or null if it would exceed the limit. */
export function buildPangramNote(dashboardLink: string): PangramNote | null {
  if (!dashboardLink) return null;
  if (countSubmittedNoteLength(NOTE_BODY, [dashboardLink]) > MAX_NOTE_LENGTH) return null;
  return { noteText: `${NOTE_BODY} ${dashboardLink}`, sourceUrl: dashboardLink };
}
